/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientinterface;

// imports needed for various methods
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author gabed
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("S̛̞̤̼͚̃́̿̋͟T̡̰̥̞́̔̒͘U͙͐Xne͕̺̅̏t̜̫̝̩̏̅̂͌");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Springfield Nuclear Reactor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Secret Control Center powered by STUXnet");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Output Log");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Love to. How about nuclear meltdown?");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Shall we play a game?");

        jScrollPane2.setViewportView(jTextPane1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Greetings Professor Dojen.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel1)
                                                .addGap(282, 282, 282))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel6))
                                        .addComponent(jButton1)
                                        .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1)))
                                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Web Service function to dump all reactor cores
    // returns a string
    private static String dumpAllCores() {
        services.NuclearPlantControl_Service service = new services.NuclearPlantControl_Service();
        services.NuclearPlantControl port = service.getNuclearPlantControlPort();
        return port.dumpAllCores();
    }

    // Web Service function to get the plant status
    // Takes a string - either "CoreStats" or "ReactorStats"
    // returns a string
    private static String getPlantStatus(java.lang.String requestedData) {
        services.NuclearPlantControl_Service service = new services.NuclearPlantControl_Service();
        services.NuclearPlantControl port = service.getNuclearPlantControlPort();
        return port.getPlantStatus(requestedData);
    }

    // Web Service function to write noise to the reactor info object
    // takes a reactor object
    // returns a reactor object
    private static services.ReactorObj getReactorInfo(services.ReactorObj reactorInfo) {
        services.NuclearPlantControl_Service service = new services.NuclearPlantControl_Service();
        services.NuclearPlantControl port = service.getNuclearPlantControlPort();
        return port.getReactorInfo(reactorInfo);
    }

    // web service function to initiate meltdown of the cores
    // returns a string
    private static String meltdownAll() {
        services.NuclearPlantControl_Service service = new services.NuclearPlantControl_Service();
        services.NuclearPlantControl port = service.getNuclearPlantControlPort();
        return port.meltdownAll();
    }
    
    // web service function to pull out x amount of control rods from a specific reactor
    // takes (int) reactorID and (int) amountToPullOut
    // returns (int) amount left
    private static int pullOutControlRods(int reactorID, int amountToPullOut) {
        services.NuclearPlantControl_Service service = new services.NuclearPlantControl_Service();
        services.NuclearPlantControl port = service.getNuclearPlantControlPort();
        return port.pullOutControlRods(reactorID, amountToPullOut);
    }

    // Web service function to restart all reactors & cores
    // returns a string
    private static String restartAll() {
        services.NuclearPlantControl_Service service = new services.NuclearPlantControl_Service();
        services.NuclearPlantControl port = service.getNuclearPlantControlPort();
        return port.restartAll();
    }

    //turns a core on or off
    //takes a (int) core ID and (int) onOff
    private static void turnCoreOnOff(int coreID, int onOff) {
        services.NuclearPlantControl_Service service = new services.NuclearPlantControl_Service();
        services.NuclearPlantControl port = service.getNuclearPlantControlPort();
        port.turnCoreOnOff(coreID, onOff);
    }
    


    // a logging function which can append styled text to
    // the jTextPanel. Contains multiple hard-coded styles.
    // takes a string text and an integer to select style.
    public void logMessage(String text, int style) {
        StyledDocument doc = jTextPane1.getStyledDocument();
        
        //Define different styles
        
        SimpleAttributeSet normal = new SimpleAttributeSet();
        StyleConstants.setFontSize(normal, 19);
        StyleConstants.setForeground(normal, Color.black);

        SimpleAttributeSet normalBold = new SimpleAttributeSet();
        StyleConstants.setFontSize(normalBold, 19);
        StyleConstants.setBold(normalBold, true);
        StyleConstants.setForeground(normalBold, Color.black);

        SimpleAttributeSet warning = new SimpleAttributeSet();
        StyleConstants.setFontSize(warning, 19);
        StyleConstants.setForeground(warning, Color.orange);

        SimpleAttributeSet error = new SimpleAttributeSet();
        StyleConstants.setFontSize(error, 19);
        StyleConstants.setForeground(error, Color.red);

        SimpleAttributeSet allgood = new SimpleAttributeSet();
        StyleConstants.setFontSize(allgood, 19);
        StyleConstants.setForeground(allgood, Color.green);
        
        // set a default fallback style
        SimpleAttributeSet textstyle = normal;
        
        // switch between different styles
        switch (style) {
            case 0:
                textstyle = normal;
                break;
            case 1:
                textstyle = allgood;
                break;
            case 2:
                textstyle = warning;
                break;
            case 3:
                textstyle = error;
                break;
            case 4:
                textstyle = normalBold;
                break;
            default:
                break;
        }
        
        // try to append to the jtextPanel
        try {
            doc.insertString(doc.getLength(), text + "\n", textstyle);

        } catch (BadLocationException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //action listener for the autmated web service demo
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // First init reactor & Core restart
        logMessage("Restarting All Reactors & Cores...", 4);
        logMessage("> "+restartAll(), 1);
        
        // Fetch the reactor status
        logMessage("\nFetching reactor status...", 4);
        logMessage(getPlantStatus("ReactorStats"), 0);

        // fetch the core status
        logMessage("\nFetching core status...", 4);
        String str = getPlantStatus("CoreStats");
        
        // status comes as a multiline string
        // can split it and change line colour based on status code
        String[] arrStr = str.split("\n", 0);
        for (String stat : arrStr) {
            if (stat.contains("0")) {
                
                //orange message - warning
                logMessage("> "+stat, 2);
            } else if (stat.contains("11")) {
                
                //red message - bad/error
                logMessage("> "+stat, 3);
            }
            else if(stat.contains("1"))
            {
                //green message - all good
                logMessage("> "+stat, 1); 
            }
        }
        
        //init a ReactorObj
        services.ReactorObj r1 = new services.ReactorObj();
        
        //call function to scrabmle reactor data
        r1 = getReactorInfo(r1);
        
        //fetch new scrambled reactor data
        logMessage("\nAttempting to write noise to reactor 1 data", 4);
        logMessage("> Sector: " + r1.getSector() , 1);
        logMessage("> Key: " + Integer.toString(r1.getKey()) , 1);
        logMessage("> ID: " + Integer.toString(r1.getReactorID()) , 1);

        // Pull out control rods from every reactor
        logMessage("\nTrying to pull out all control rods from reactor 1", 4);
        logMessage("> Sucess, pulled out 9 rods, " + (Integer.toString(pullOutControlRods(1,9))) + " left",1);
        logMessage("\nTrying to pull out all control rods from reactor 2", 4);
        logMessage("> Sucess, pulled out 9 rods, " + (Integer.toString(pullOutControlRods(2,9))) + " left",1);
        logMessage("\nTrying to pull out all control rods from reactor 3", 4);
        logMessage("> Sucess, pulled out 9 rods, " + (Integer.toString(pullOutControlRods(3,9))) + " left",1);
        
        // Dump a core to test
        logMessage("\nDumping Core 1 to test...", 4);
        logMessage("> Core 1 dumped", 1);
        turnCoreOnOff(0, 0);
        
        // fetch core stat to show core has really been dumped
        logMessage("\nFetching core status...", 4);
        str = getPlantStatus("CoreStats");
        
        // core stat is multiline so let's split and parse the status codes
        arrStr = str.split("\n", 0);
        for (String stat : arrStr) {
            if (stat.contains("0")) {
                logMessage("> "+stat, 2);
            } else if (stat.contains("11")) {
                logMessage("> "+stat, 3);
            }
            else if(stat.contains("1"))
            {
                logMessage("> "+stat, 1); 
            }
        }
        
        // dump all the cores
        logMessage("\nDumping all cores...", 4);
        logMessage("> "+dumpAllCores(), 1);
        
        // fetch the core status
        logMessage("\nFetching core status...", 4);
        str = getPlantStatus("CoreStats");
        
        //split the core status and parse the core statuses
        arrStr = str.split("\n", 0);
        for (String stat : arrStr) {
            if (stat.contains("0")) {
                logMessage("> "+stat, 2);
            } else if (stat.contains("11")) {
                logMessage("> "+stat, 3);
            }
            else if(stat.contains("1"))
            {
                logMessage("> "+stat, 1); 
            }
        }
        
        // everything wortks, we have full control of the reactor
        logMessage("\n> Full control of Springfield Nuclear Power Plant achieved", 1);
        
        // reseting the reactors and cores
        logMessage("\nRestoring plant to initial state", 4);
        logMessage("> " + restartAll(), 1);
        
        // begin meltdown protocol
        logMessage("\nBegining Nuclear Meltdown Protocol...", 4);
        
        
        // first pull out all control rods
        logMessage("\nTrying to pull out all control rods from reactor 1", 4);
        logMessage("> Sucess, pulled out 9 rods, " + (Integer.toString(pullOutControlRods(1,9))) + " left",1);
        logMessage("\nTrying to pull out all control rods from reactor 2", 4);
        logMessage("> Sucess, pulled out 9 rods, " + (Integer.toString(pullOutControlRods(2,9))) + " left",1);
        logMessage("\nTrying to pull out all control rods from reactor 3", 4);
        logMessage("> Sucess, pulled out 9 rods, " + (Integer.toString(pullOutControlRods(3,9))) + " left",1);
        
        // begin melting the cores down
        logMessage("\n> " + meltdownAll(), 3);
        
        // license warning message
        logMessage("\n> You are using the FREE STUXnet version, to initiate global nuclear meltdowns please buy the premium license", 0);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables



}
